# Generated by Django 4.1.1 on 2022-10-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_product_size_alter_product_testo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='testo',
            field=models.CharField(blank=True, choices=[('Традиционное тесто,', 'Традиционное тесто,'), ('Тонкое тесто,', 'Тонкое тесто,')], default=None, max_length=100, null=True),
        ),
    ]
