# Generated by Django 4.1.1 on 2022-10-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='entrance',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Подьезд'),
        ),
        migrations.AddField(
            model_name='order',
            name='flat',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='order',
            name='floor',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='order',
            name='house',
            field=models.CharField(default='', max_length=250, verbose_name='Дом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default='', max_length=250, verbose_name='Улица'),
            preserve_default=False,
        ),
    ]
